name: SimpleWarps
main: me.NerdsWBNerds.SimpleWarps.SimpleWarps
version: 3.2
commands:
   warp:
      description: Show list of warp, or warp to or warp other people to a warp.
      usage: /warp, /warp <warp_name>, /warp <player_name> <warp_name>
      aliases: [swarp]
   setwarp:
      description: Set a warp at your location.
      usage: /setwarp <warp_name>
      aliases: [addwarp]
   delwarp:
      description: Delete warp by name.
      usage: /delwarp <warp_name>
      aliases: [deletewarp, removewarp]